// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsGo-5I0i8qK_oJ6QJGqfYj4m1poaV1Y',
    appId: '1:291464502602:web:d539f05e8863cc7ad175b3',
    messagingSenderId: '291464502602',
    projectId: 'monkeydbar-c5693',
    authDomain: 'monkeydbar-c5693.firebaseapp.com',
    storageBucket: 'monkeydbar-c5693.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXYYbgnio-pbabYHI2JH4QzvSl5uNBp0c',
    appId: '1:291464502602:android:4f8d0566f810c9eed175b3',
    messagingSenderId: '291464502602',
    projectId: 'monkeydbar-c5693',
    storageBucket: 'monkeydbar-c5693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXTRtSTm2FuGrTVg_eWbpA_spHsm3kPN0',
    appId: '1:291464502602:ios:b4fbc395120daed6d175b3',
    messagingSenderId: '291464502602',
    projectId: 'monkeydbar-c5693',
    storageBucket: 'monkeydbar-c5693.firebasestorage.app',
    iosBundleId: 'com.example.monkeyDBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXTRtSTm2FuGrTVg_eWbpA_spHsm3kPN0',
    appId: '1:291464502602:ios:b4fbc395120daed6d175b3',
    messagingSenderId: '291464502602',
    projectId: 'monkeydbar-c5693',
    storageBucket: 'monkeydbar-c5693.firebasestorage.app',
    iosBundleId: 'com.example.monkeyDBar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgsGo-5I0i8qK_oJ6QJGqfYj4m1poaV1Y',
    appId: '1:291464502602:web:2e848126a027d336d175b3',
    messagingSenderId: '291464502602',
    projectId: 'monkeydbar-c5693',
    authDomain: 'monkeydbar-c5693.firebaseapp.com',
    storageBucket: 'monkeydbar-c5693.firebasestorage.app',
  );
}
